### PR TITLE
Principal Component Analysis

### PR DESCRIPTION
**Pull request by jeremyfix**
I propose to open a "Dimensionality Reduction" section and this PR provides a simple script computing the PCA with two illustrations :
- with random points in 2D to illustrate the projection vectors that are computed
- with 28x28 digits projected in 2D. The top plot shows the digits projected in the space spanned by the first 2 principal vectors. The bottom plot shows the projection vectors and permit to make sense of the top plot since the vectors clearly indicate the digits they separate.

### CODE REVIEW

**Comment by rougier** [comment]
Good idea. Can you post the resulting figures here ?

**Comment by jeremyfix** [comment]
Here they are. 

random_points


digits

And the program output 

```
$ python3 pca.py 
Random data example
----------------------------------------------------------------------
95.96% of the variance along the first axis (green)
4.04% of the variance along the second axis (red)

Digits example
----------------------------------------------------------------------
47.67% of the variance is kept with 10 components
```

**Comment by rougier** [comment]
Thanks. You can use  `alpha=0.25` in scatter to get a better sense of the distribution.

**Comment by jeremyfix** [comment]
This is definitely a good idea.  

The updated plots :

random_points
digits

**Comment by rougier** [comment]
Didn't check you did not modified the README. Can you make a PR?

**Pull request merged**
